apiVersion: apps/v1
kind: Deployment
# include
metadata:
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: 9three3four/fastapi-app:v1
        ports:
        - containerPort: 8080
